[package]
name = "tpx-py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
tpx-core.workspace = true
tpx-engine.workspace = true
pyo3.workspace = true
thiserror.workspace = true
