name: OSV-Scanner

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0'

env:
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: "node24"

jobs:
  scan:
    name: Google OSV Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --lockfile=requirements.txt
